/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Koneksi;

/**
 *
 * @author User
 */
public class ViewBarang extends javax.swing.JFrame {

    /**
     * Creates new form ViewBarang
     */
    public ViewBarang() {
        initComponents();
        tampildata();
    }
    void tampildata() {
    DefaultTableModel table = new DefaultTableModel();
        table.addColumn("id");
        table.addColumn("nama");
        table.addColumn("jenis");
        table.addColumn("jumlah");

        TB_Barang.setModel(table);

        try {
            Koneksi Koneksi = new Koneksi();
            Koneksi.koneksidatabase();
            String queryTampil = "select * from db_uas_15311608";

            ResultSet res = Koneksi.state.executeQuery(queryTampil);

            while (res.next()) {
                table.addRow(new Object[]{
                    res.getString("id"), res.getString("nama"), res.getString("Jenis"), res.getString("Jumlah")
                });
                TB_Barang.setModel(table);
                

            }

        } catch (SQLException e) {
            System.err.println(""+e);
        }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JT_Id = new javax.swing.JTextField();
        JT_Nama = new javax.swing.JTextField();
        JT_Jenis = new javax.swing.JTextField();
        JT_Jumlah = new javax.swing.JTextField();
        BTN_Ubah = new javax.swing.JButton();
        BTN_Hapus = new javax.swing.JButton();
        BTN_Tutup = new javax.swing.JButton();
        BTN_Baru = new javax.swing.JButton();
        BTN_Simpan = new javax.swing.JButton();
        BTN_Berish = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_Barang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("id :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 10, 20, -1));

        jLabel2.setText("Nama Barang :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, -1));

        jLabel3.setText("Jenis Barang :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setText("Jumlah Barang :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        JT_Id.setEnabled(false);
        getContentPane().add(JT_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 110, -1));

        JT_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_NamaActionPerformed(evt);
            }
        });
        getContentPane().add(JT_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 290, -1));
        getContentPane().add(JT_Jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 290, -1));

        JT_Jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_JumlahActionPerformed(evt);
            }
        });
        getContentPane().add(JT_Jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 290, -1));

        BTN_Ubah.setText("Ubah");
        BTN_Ubah.setEnabled(false);
        getContentPane().add(BTN_Ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        BTN_Hapus.setText("Hapus");
        BTN_Hapus.setEnabled(false);
        BTN_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HapusActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        BTN_Tutup.setText("Tutup");
        BTN_Tutup.setEnabled(false);
        getContentPane().add(BTN_Tutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        BTN_Baru.setText("Baru");
        BTN_Baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BaruActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_Baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        BTN_Simpan.setText("Simpan");
        BTN_Simpan.setEnabled(false);
        BTN_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        BTN_Berish.setText("Bersih");
        BTN_Berish.setEnabled(false);
        getContentPane().add(BTN_Berish, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        TB_Barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TB_Barang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 127, 540, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_NamaActionPerformed

    private void JT_JumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_JumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_JumlahActionPerformed

    private void BTN_BaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BaruActionPerformed
        // TODO add your handling code here:
        BTN_Simpan.setEnabled(true);
        BTN_Baru.setText("batal");
    }//GEN-LAST:event_BTN_BaruActionPerformed

    private void BTN_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SimpanActionPerformed
        // TODO add your handling code here:
        String nama = JT_Nama.getText();
        Double jenis = Double.parseDouble(JT_Jenis.getText());
        Double jumlah = Double.parseDouble(JT_Jumlah.getText());
        
        
        Koneksi Koneksi = new Koneksi();
        Koneksi.koneksidatabase();

        try {
            String query = "insert into db_uas_15311608 (nama,jenis,jumlah) values ('" + nama + "','" + jenis + "','" + jumlah+ "')";
            
            Koneksi.state.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Database Berhasil Disimpan");
            Koneksi.connect.close();
        } catch (SQLException e) {
            System.err.println("" + e);        // TODO add your handling code here}
            
        }
    }                                          

    private void jt_areaMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        try {
            int baris = TB_Barang.getSelectedRow();//mengambil urutan baris dari table yang ada
            JT_Id.setText(TB_Barang.getValueAt(baris, 0).toString());
            JT_Nama.setText(TB_Barang.getValueAt(baris, 1).toString());
            JT_Jenis.setText(TB_Barang.getValueAt(baris, 2).toString());
            JT_Jumlah.setText(TB_Barang.getValueAt(baris, 3).toString());
        } catch (Exception e) {
            System.err.println("Error : " + e);
        }  
    }//GEN-LAST:event_BTN_SimpanActionPerformed

    private void BTN_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HapusActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(JT_Id.getText());
            String queryhapus =
                    "delete from tbl_barang where nama=('"+id+"')";
            Koneksi ayu = new Koneksi();
            ayu.koneksidatabase();
            ayu.state.executeUpdate(queryhapus);
            JOptionPane.showMessageDialog(null, "Data hapus");
            tampildata();
            
        } catch (SQLException e) {
            System.err.println(""+e);
        }
    }//GEN-LAST:event_BTN_HapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Baru;
    private javax.swing.JButton BTN_Berish;
    private javax.swing.JButton BTN_Hapus;
    private javax.swing.JButton BTN_Simpan;
    private javax.swing.JButton BTN_Tutup;
    private javax.swing.JButton BTN_Ubah;
    private javax.swing.JTextField JT_Id;
    private javax.swing.JTextField JT_Jenis;
    private javax.swing.JTextField JT_Jumlah;
    private javax.swing.JTextField JT_Nama;
    private javax.swing.JTextField JT_id;
    private javax.swing.JTextField JT_id1;
    private javax.swing.JTable TB_Barang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
